from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Mapping, Sequence

import numpy as np


@dataclass(frozen=True)
class ExactCandidateEvaluation:
    """A true-cost record that can safely be reused by the closed loop."""

    success: bool
    total_cost: float | None
    message: str
    source: str
    lp_solve_performed: bool = False
    logic_precheck_rejected: bool = False

    def __post_init__(self) -> None:
        if self.success:
            if self.total_cost is None or not np.isfinite(float(self.total_cost)):
                raise ValueError("成功的 exact evaluation 必须包含有限 total_cost")
            if self.logic_precheck_rejected:
                raise ValueError("成功 evaluation 不能同时是 logic precheck rejection")
        elif self.total_cost is not None and not np.isfinite(float(self.total_cost)):
            raise ValueError("失败 evaluation 的 total_cost 必须为 None 或有限数")
        if self.logic_precheck_rejected and self.lp_solve_performed:
            raise ValueError("logic precheck rejection 不能同时执行 LP solve")

    def as_dict(self) -> dict[str, object]:
        return {
            "success": bool(self.success),
            "total_cost": float(self.total_cost) if self.total_cost is not None else None,
            "message": str(self.message),
            "source": str(self.source),
            "lp_solve_performed": bool(self.lp_solve_performed),
            "logic_precheck_rejected": bool(self.logic_precheck_rejected),
        }


ExactEvaluator = Callable[[int], ExactCandidateEvaluation]
TrueCostEncoder = Callable[[float], int]
HardLogicEvaluator = Callable[[Sequence[int]], bool]


@dataclass(frozen=True)
class ClosedLoopBudgets:
    """Shared candidate-acceptance budgets, independent of candidate source."""

    max_proposals: int
    max_new_exact_evaluations: int
    max_actual_ed_lp_solves: int | None
    max_threshold_updates: int
    max_consecutive_nonimproving_marked: int
    max_same_encoded_threshold_updates: int
    max_auxiliary_syndrome_rejections: int

    def __post_init__(self) -> None:
        for name in (
            "max_proposals",
            "max_new_exact_evaluations",
            "max_threshold_updates",
            "max_consecutive_nonimproving_marked",
            "max_same_encoded_threshold_updates",
            "max_auxiliary_syndrome_rejections",
        ):
            if int(getattr(self, name)) <= 0:
                raise ValueError(f"{name} 必须为正整数")
        if (
            self.max_actual_ed_lp_solves is not None
            and int(self.max_actual_ed_lp_solves) <= 0
        ):
            raise ValueError("max_actual_ed_lp_solves 必须为正整数或 None")


@dataclass(frozen=True)
class CandidateProposal:
    """A candidate generated by BBHT or a future classical sampler.

    It intentionally contains no true cost. The shared acceptance loop is the
    only component allowed to obtain a true cost and update the incumbent.
    """

    candidate_index: int
    source_method: str
    auxiliary_accepted: bool
    surrogate_integer_cost: int
    grover_iterations: int = 0
    oracle_calls: int = 0
    metadata: Mapping[str, object] = field(default_factory=dict)


@dataclass(frozen=True)
class CandidateDecision:
    candidate_status: str
    rejection_reason: str | None
    accepted_update: bool
    true_improvement: bool
    verification_source: str | None
    exact_record: ExactCandidateEvaluation | None
    candidate_true_cost: float | None
    is_training_state: bool
    is_repeated_candidate: bool
    is_unique_candidate: bool
    is_cache_hit: bool
    new_exact_evaluation_attempted: bool
    new_edlp_solve_performed: bool
    logic_feasible: bool
    surrogate_better: bool
    surrogate_marked: bool
    cache_confirmed_improvement: bool
    new_edlp_confirmed_improvement: bool
    nontraining_true_improvement: bool
    first_nontraining_improvement: bool
    candidate_marked_hit_count: int
    candidate_repeat_count: int
    threshold_before: float
    threshold_after: float
    encoded_threshold_before: int
    encoded_threshold_after: int
    encoded_threshold_changed: bool
    quantization_stagnation: bool
    new_exact_evaluation_attempts_added: int
    actual_ed_lp_solves_added: int
    logic_precheck_rejections_added: int
    should_grow_window: bool
    reset_window: bool
    stop_reason: str | None

    def trace_fields(self) -> dict[str, object]:
        return {
            "auxiliary_accepted": self.rejection_reason != "auxiliary_syndrome_rejected",
            "hard_logic_feasible": bool(self.logic_feasible),
            "surrogate_better": bool(self.surrogate_better),
            "surrogate_marked": bool(self.surrogate_marked),
            "joint_feasible_and_better": bool(self.surrogate_marked),
            "candidate_status": self.candidate_status,
            "candidate_cache_hit": bool(self.is_cache_hit),
            "new_exact_evaluation_attempted": bool(
                self.new_exact_evaluation_attempted
            ),
            "new_edlp_solve_performed": bool(self.new_edlp_solve_performed),
            "candidate_marked_hit_count": int(self.candidate_marked_hit_count),
            "candidate_repeat_count": int(self.candidate_repeat_count),
            "is_training_state": bool(self.is_training_state),
            "is_repeated_candidate": bool(self.is_repeated_candidate),
            "is_unique_candidate": bool(self.is_unique_candidate),
            "verification_source": self.verification_source,
            "exact_evaluation": (
                self.exact_record.as_dict() if self.exact_record is not None else None
            ),
            "exact_cost": self.candidate_true_cost,
            "new_exact_evaluation_attempts_added": int(
                self.new_exact_evaluation_attempts_added
            ),
            "actual_ed_lp_solves_added": int(self.actual_ed_lp_solves_added),
            "logic_precheck_rejections_added": int(
                self.logic_precheck_rejections_added
            ),
            "ed_lp_calls_added": int(self.new_exact_evaluation_attempts_added),
            "true_improvement": bool(self.true_improvement),
            "accepted_update": bool(self.accepted_update),
            "cache_confirmed_improvement": bool(self.cache_confirmed_improvement),
            "new_edlp_confirmed_improvement": bool(
                self.new_edlp_confirmed_improvement
            ),
            "nontraining_true_improvement": bool(self.nontraining_true_improvement),
            "first_nontraining_improvement": bool(self.first_nontraining_improvement),
            "true_threshold_before": float(self.threshold_before),
            "true_threshold_after": float(self.threshold_after),
            "encoded_threshold_before": int(self.encoded_threshold_before),
            "encoded_threshold_after": int(self.encoded_threshold_after),
            "encoded_threshold_changed": bool(self.encoded_threshold_changed),
            "quantization_stagnation": bool(self.quantization_stagnation),
            "threshold_updated": bool(self.accepted_update),
            "rejection_reason": self.rejection_reason,
        }


@dataclass
class ClosedLoopState:
    incumbent_index: int
    incumbent_true_cost: float
    encoded_threshold: int
    exact_cache: dict[int, ExactCandidateEvaluation]
    training_indices: frozenset[int]
    num_x_qubits: int
    encode_true_cost: TrueCostEncoder
    hard_logic_is_feasible: HardLogicEvaluator | None
    budgets: ClosedLoopBudgets
    initial_incumbent_index: int
    initial_incumbent_true_cost: float
    threshold_history: list[dict[str, object]]
    seen_candidates: set[int] = field(default_factory=set)
    marked_candidate_hits: dict[int, int] = field(default_factory=dict)
    repeated_candidate_hits: dict[int, int] = field(default_factory=dict)
    proposals_used: int = 0
    new_exact_evaluation_attempts: int = 0
    actual_ed_lp_solves: int = 0
    logic_precheck_rejections: int = 0
    cached_exact_lookups: int = 0
    auxiliary_syndrome_rejections: int = 0
    threshold_updates: int = 0
    same_encoded_threshold_updates: int = 0
    consecutive_nonimproving_marked: int = 0
    first_nontraining_improvement_index: int | None = None


def create_closed_loop_state(
    *,
    initial_incumbent_index: int,
    initial_exact_cache: Mapping[int, ExactCandidateEvaluation],
    training_indices: Sequence[int],
    num_x_qubits: int,
    encode_true_cost: TrueCostEncoder,
    hard_logic_is_feasible: HardLogicEvaluator | None,
    budgets: ClosedLoopBudgets,
) -> ClosedLoopState:
    cache = {int(index): record for index, record in initial_exact_cache.items()}
    incumbent_index = int(initial_incumbent_index)
    initial_record = cache.get(incumbent_index)
    if initial_record is None or not initial_record.success or initial_record.total_cost is None:
        raise ValueError("初始 incumbent 必须存在于成功的 exact cache 中")
    if int(num_x_qubits) <= 0:
        raise ValueError("num_x_qubits 必须为正整数")
    incumbent_cost = float(initial_record.total_cost)
    threshold = int(encode_true_cost(incumbent_cost))
    return ClosedLoopState(
        incumbent_index=incumbent_index,
        incumbent_true_cost=incumbent_cost,
        encoded_threshold=threshold,
        exact_cache=cache,
        training_indices=frozenset(int(index) for index in training_indices),
        num_x_qubits=int(num_x_qubits),
        encode_true_cost=encode_true_cost,
        hard_logic_is_feasible=hard_logic_is_feasible,
        budgets=budgets,
        initial_incumbent_index=incumbent_index,
        initial_incumbent_true_cost=incumbent_cost,
        threshold_history=[
            {
                "update_number": 0,
                "incumbent_index": incumbent_index,
                "incumbent_bitstring": _bitstring_from_index(
                    incumbent_index, int(num_x_qubits)
                ),
                "true_threshold": incumbent_cost,
                "encoded_threshold": threshold,
                "source": "initial_exact_cache",
            }
        ],
    )


def accept_candidate_proposal(
    state: ClosedLoopState,
    proposal: CandidateProposal,
    *,
    evaluate_candidate: ExactEvaluator,
) -> CandidateDecision:
    """Charge and validate one proposal without any validation-landscape input."""

    if state.proposals_used >= int(state.budgets.max_proposals):
        raise RuntimeError("proposal budget 已耗尽，不能免费重试")
    candidate_index = int(proposal.candidate_index)
    if candidate_index < 0 or candidate_index >= 2 ** int(state.num_x_qubits):
        raise ValueError("candidate_index 超出搜索空间")

    state.proposals_used += 1
    threshold_before = float(state.incumbent_true_cost)
    encoded_before = int(state.encoded_threshold)
    is_repeated = candidate_index in state.seen_candidates
    state.seen_candidates.add(candidate_index)
    is_training = candidate_index in state.training_indices
    bits = _bits_from_index(candidate_index, state.num_x_qubits)
    logic_feasible = bool(
        state.hard_logic_is_feasible is None
        or state.hard_logic_is_feasible(bits)
    )
    surrogate_better = bool(int(proposal.surrogate_integer_cost) < encoded_before)
    surrogate_marked = bool(logic_feasible and surrogate_better)

    status = "measured_unmarked"
    rejection_reason: str | None = None
    exact_record: ExactCandidateEvaluation | None = None
    verification_source: str | None = None
    candidate_true_cost: float | None = None
    is_cache_hit = False
    new_attempt = 0
    actual_lp = 0
    logic_rejections = 0
    true_improvement = False
    cache_confirmed_improvement = False
    new_edlp_confirmed_improvement = False
    nontraining_true_improvement = False
    first_nontraining_improvement = False
    marked_hit_count = 0
    marked_repeat_count = 0
    should_grow_window = False
    reset_window = False
    stop_reason: str | None = None
    encoded_changed = False
    quantization_stagnation = False

    if not proposal.auxiliary_accepted:
        status = "auxiliary_syndrome_rejected"
        rejection_reason = "auxiliary_syndrome_rejected"
        state.auxiliary_syndrome_rejections += 1
        if (
            state.auxiliary_syndrome_rejections
            >= int(state.budgets.max_auxiliary_syndrome_rejections)
        ):
            stop_reason = "max_auxiliary_syndrome_rejections_reached"
    elif not logic_feasible:
        status = "measured_hard_logic_infeasible"
        rejection_reason = "hard_logic_infeasible"
        should_grow_window = True
    elif not surrogate_better:
        status = "measured_unmarked"
        rejection_reason = "surrogate_unmarked"
        should_grow_window = True
    else:
        marked_hit_count = state.marked_candidate_hits.get(candidate_index, 0) + 1
        state.marked_candidate_hits[candidate_index] = marked_hit_count
        marked_repeat_count = max(0, marked_hit_count - 1)
        if marked_repeat_count:
            state.repeated_candidate_hits[candidate_index] = marked_repeat_count
        if candidate_index in state.exact_cache:
            is_cache_hit = True
            state.cached_exact_lookups += 1
            exact_record = state.exact_cache[candidate_index]
            verification_source = str(exact_record.source)
        elif (
            state.new_exact_evaluation_attempts
            >= int(state.budgets.max_new_exact_evaluations)
        ):
            status = "new_ed_lp_budget_exhausted"
            rejection_reason = "new_exact_evaluation_budget_exhausted"
            stop_reason = "max_new_ed_lp_calls_reached"
        elif (
            state.budgets.max_actual_ed_lp_solves is not None
            and state.actual_ed_lp_solves
            >= int(state.budgets.max_actual_ed_lp_solves)
        ):
            status = "actual_ed_lp_budget_exhausted"
            rejection_reason = "actual_ed_lp_solve_budget_exhausted"
            stop_reason = "max_actual_ed_lp_solves_reached"
        else:
            try:
                exact_record = evaluate_candidate(candidate_index)
            except Exception as exc:  # pragma: no cover - defensive integration path
                exact_record = ExactCandidateEvaluation(
                    success=False,
                    total_cost=None,
                    message=f"exact evaluator raised: {exc}",
                    source="new_exact_evaluation_exception",
                )
            if not isinstance(exact_record, ExactCandidateEvaluation):
                raise TypeError("evaluate_candidate 必须返回 ExactCandidateEvaluation")
            state.exact_cache[candidate_index] = exact_record
            state.new_exact_evaluation_attempts += 1
            new_attempt = 1
            if exact_record.lp_solve_performed:
                state.actual_ed_lp_solves += 1
                actual_lp = 1
            if exact_record.logic_precheck_rejected:
                state.logic_precheck_rejections += 1
                logic_rejections = 1
            verification_source = str(exact_record.source)

        if exact_record is not None:
            if exact_record.success and exact_record.total_cost is not None:
                candidate_true_cost = float(exact_record.total_cost)
                true_improvement = bool(candidate_true_cost < threshold_before)
            if true_improvement:
                state.incumbent_index = candidate_index
                state.incumbent_true_cost = float(candidate_true_cost)
                state.encoded_threshold = int(
                    state.encode_true_cost(state.incumbent_true_cost)
                )
                encoded_changed = bool(state.encoded_threshold != encoded_before)
                quantization_stagnation = not encoded_changed
                state.threshold_updates += 1
                if encoded_changed:
                    state.same_encoded_threshold_updates = 0
                else:
                    state.same_encoded_threshold_updates += 1
                state.consecutive_nonimproving_marked = 0
                reset_window = True
                status = "true_incumbent_improved"
                cache_confirmed_improvement = bool(is_cache_hit)
                new_edlp_confirmed_improvement = bool(not is_cache_hit and actual_lp)
                nontraining_true_improvement = bool(not is_training)
                if nontraining_true_improvement and state.first_nontraining_improvement_index is None:
                    state.first_nontraining_improvement_index = candidate_index
                    first_nontraining_improvement = True
                state.threshold_history.append(
                    {
                        "update_number": int(state.threshold_updates),
                        "trial_number": int(state.proposals_used),
                        "incumbent_index": int(state.incumbent_index),
                        "incumbent_bitstring": _bitstring_from_index(
                            state.incumbent_index, state.num_x_qubits
                        ),
                        "true_threshold": float(state.incumbent_true_cost),
                        "encoded_threshold": int(state.encoded_threshold),
                        "encoded_threshold_changed": bool(encoded_changed),
                        "verification_source": verification_source,
                    }
                )
                if (
                    state.same_encoded_threshold_updates
                    >= int(state.budgets.max_same_encoded_threshold_updates)
                ):
                    stop_reason = "same_encoded_threshold_update_limit"
                elif state.threshold_updates >= int(state.budgets.max_threshold_updates):
                    stop_reason = "max_threshold_updates_reached"
            else:
                state.consecutive_nonimproving_marked += 1
                should_grow_window = True
                if exact_record.success:
                    status = "marked_but_not_true_improvement"
                elif exact_record.logic_precheck_rejected:
                    status = "marked_logic_precheck_rejected"
                else:
                    status = "marked_exact_evaluation_failed"
                if (
                    state.consecutive_nonimproving_marked
                    >= int(state.budgets.max_consecutive_nonimproving_marked)
                ):
                    stop_reason = "max_consecutive_nonimproving_marked_reached"

    return CandidateDecision(
        candidate_status=status,
        rejection_reason=rejection_reason,
        accepted_update=true_improvement,
        true_improvement=true_improvement,
        verification_source=verification_source,
        exact_record=exact_record,
        candidate_true_cost=candidate_true_cost,
        is_training_state=is_training,
        is_repeated_candidate=is_repeated,
        is_unique_candidate=not is_repeated,
        is_cache_hit=is_cache_hit,
        new_exact_evaluation_attempted=bool(new_attempt),
        new_edlp_solve_performed=bool(actual_lp),
        logic_feasible=logic_feasible,
        surrogate_better=surrogate_better,
        surrogate_marked=surrogate_marked,
        cache_confirmed_improvement=cache_confirmed_improvement,
        new_edlp_confirmed_improvement=new_edlp_confirmed_improvement,
        nontraining_true_improvement=nontraining_true_improvement,
        first_nontraining_improvement=first_nontraining_improvement,
        candidate_marked_hit_count=marked_hit_count,
        candidate_repeat_count=marked_repeat_count,
        threshold_before=threshold_before,
        threshold_after=float(state.incumbent_true_cost),
        encoded_threshold_before=encoded_before,
        encoded_threshold_after=int(state.encoded_threshold),
        encoded_threshold_changed=encoded_changed,
        quantization_stagnation=quantization_stagnation,
        new_exact_evaluation_attempts_added=new_attempt,
        actual_ed_lp_solves_added=actual_lp,
        logic_precheck_rejections_added=logic_rejections,
        should_grow_window=should_grow_window,
        reset_window=reset_window,
        stop_reason=stop_reason,
    )


def _bits_from_index(index: int, num_qubits: int) -> tuple[int, ...]:
    return tuple((int(index) >> qubit) & 1 for qubit in range(int(num_qubits)))


def _bitstring_from_index(index: int, num_qubits: int) -> str:
    return "".join(str(bit) for bit in _bits_from_index(index, num_qubits))
